# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Tao's Blog"
email: litao.buptsse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  On The Way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.guaver.info" # the base hostname & protocol for your site
twitter_username: "litao_bupt"
github_username:  "litao-buptsse"

# Build settings
markdown: kramdown
