# Site settings
title: Tao Li's Blog
description: "Tao Li's Blog"
# baseurl: "/space-jekyll-template" # the subpath of your site
url: "http://litao-buptsse.github.io"

# User settings
username: Tao Li
user_title: Tao Li
email: litao.buptsse@gmail.com.com
twitter_username: litao_bupt
github_username:  litao-buptsse
gplus_username:  litao.buptsse
disqus_username: litao.buptsse

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: bigdatakit
    url: https://github.com/litao-buptsse/bigdatakit
  - name: hadoop-extras
    url: https://github.com/litao-buptsse/hadoop-extras
  - name: flume-hive-batch-sink
    url: https://github.com/litao-buptsse/flume-hive-batch-sink
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
